# Generated by Django 5.2 on 2025-04-24 01:31

import predicciones.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=predicciones.models.subir_imagen)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('prediccion', models.IntegerField(blank=True, null=True)),
                ('confianza', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
